<?php

/**
 * @file
 * Block Entity
 */

/**
 * Implements hook_menu().
 */
function virtual_wardrobe_menu() {
  $items['add/%ctools_js/review/%/%'] = array(
    'page callback' => 'virtual_wardrobe_vestuario',
    'page arguments'  => array(1, 3, 4),
    'access arguments' => array('access content'),
  );
  return $items;
}


function virtual_wardrobe_vestuario($js = NULL, $nid = NULL, $path = NULL) {
  if ($js) {
    // Required includes for ctools to work:
    ctools_include('modal');
    ctools_include('ajax');
    ctools_add_js('ajax-responder');
  }
  global $user;
  $node = node_load($nid);
  $taxonomia = taxonomy_term_load($node->field_category['und'][0]['tid']);
  $id_product = field_get_items('node', $node, 'field_product');
  $product = commerce_product_load($id_product[0]['product_id']);
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'vestuario')
    ->propertyCondition('title', $user->uid)
    ->range(0, 1);
  $result = $query->execute();
  if (isset($result['node'])) {
    $nid_result = reset($result['node']);
    $node_vestier = node_load($nid_result->nid);

    if($taxonomia->name == 'Blusas' || $taxonomia->name == 'Camisas' || $taxonomia->name == 'Camisetas' || $taxonomia->name == 'Chaquetas' || $taxonomia->name == 'Tops' || $taxonomia->name == 'Sacos'){
      $node_vestier->field_pecho['und'][0] = $product->field_images['und'][0];
    }else{
      $node_vestier->field_piernas['und'][0] = $product->field_images['und'][0];
    }
    node_save($node_vestier);
  }else{
    $node_create = new stdClass();
    $node_create->type = 'vestuario';
    node_object_prepare($node_create);
    $node_create->title = $user->uid;
    // ...more node properties...
    node_save($node_create);
    //var_dump($new); // => N
  }

  //dpm($product->field_images['und'][0]);
  if($path == 8){
    $redirect = 'collection/casual';
  }elseif ($path == 11) {
    $redirect = 'collection/formal';
  }elseif ($path == 10) {
    $redirect = 'collection/otoño-invierno';
  }elseif ($path == 9) {
    $redirect = 'collection/primavera-verano';
  }else{
    $redirect = 'products';
  }
  $commands[] = ctools_ajax_command_redirect($redirect);
  // you can also use ctools_ajax_command_reload() –  xurshid29
  print ajax_render($commands);
  drupal_exit();
  //return ctools_modal_render(t('Vestuario'), 'hola');
}

/**
 * Implement hook_page_alter.
 */
function virtual_wardrobe_page_alter(&$page) {
  drupal_add_js(array(
    'vestier-virtual' => array(
      'modalSize' => array(
       'type' => 'fixed',
       'width' => 50,
       'height' => 50,
      ),
    ),
  ), 'setting');
}

function virtual_wardrobe_vestuario_lateral($nid){
  $form_state = array();
  $form_state['build_info']['args'] = $nid;
  return render(drupal_get_form('virtual_wardrobe_vesturio_form', $form_state));

}

function virtual_wardrobe_vesturio_form($node, &$form_state) {
  $form['#prefix'] = '<div id="virtual-wardrobe-vestier">';
  $form['#suffix'] = '</div>';
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Añadir al vestidor'),
    '#ajax' => array(
      'callback' => 'virtual_wardrobe_vesturio_callback',
      'wrapper' => 'region-page-top',
    ),
    '#submit' => array('virtual_wardrobe_vesturio_submit'),
  );

  return $form;
}

function virtual_wardrobe_vesturio_callback($form, &$form_state){
  return $form;
}

function virtual_wardrobe_vesturio_submit($form, &$form_state){
  $nid = $form_state['build_info']['args'][0]['build_info']['args'];
  global $user;
  $node = node_load($nid);
  $taxonomia = taxonomy_term_load($node->field_category['und'][0]['tid']);
  $id_product = field_get_items('node', $node, 'field_product');
  $product = commerce_product_load($id_product[0]['product_id']);
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'vestuario')
    ->propertyCondition('title', 1)
    ->range(0, 1);
  $result = $query->execute();
  if (isset($result['node'])) {
    $nid_result = reset($result['node']);
    $node_vestier = node_load($nid_result->nid);
    if($taxonomia->name == 'Blusas' || $taxonomia->name == 'Camisas' || $taxonomia->name == 'Camisetas' || $taxonomia->name == 'Chaquetas' || $taxonomia->name == 'Tops' || $taxonomia->name == 'Sacos'){
      $node_vestier->field_pecho['und'][0] = $product->field_images['und'][0];
    }else{
      $node_vestier->field_piernas['und'][0] = $product->field_images['und'][0];
    }
    node_save($node_vestier);
  }
  //$form['#redirect'] = "products";
}

function virtual_wardrobe_form_alter(&$form, &$form_state, $form_id) {
  switch ($form_id) {
    case 'commerce_addressbook_customer_profile_form':
      $form['commerce_customer_address'][LANGUAGE_NONE][0]['#title'] = t('Dirección');
      break;
  }
}
